paladin:
  dynamic-datasource-enabled: 'true'
  dynamic:
    mybatis:
      mapper-location: classpath:dynamic/mapper/**/*.xml
      type-aliases-package: com.paladin.qos.dynamic.model
    source[0]:
      name: fuyou
      url: jdbc:sqlserver://10.1.1.36:1044;database=wcdbsz
      username: jswj
      password: jswj2019
    source[1]:
      name: gongwei
      url: jdbc:oracle:thin:@//10.9.0.165:1521/ksdaga
      username: phis_wj
      password: phis_wj
    source[2]:
      name: jcyl
      url: jdbc:oracle:thin:@//10.9.0.12:1521/ksdaga
      username: phis_wj
      password: 123456
    source[3]:
      name: yiyuan-dyrmyy
      url: jdbc:oracle:thin:@//10.9.1.34:1521/orcl
      username: di_ehr467170249
      password: neusoft
