paladin:
  dynamic-datasource-enabled: 'true'
  dynamic:
    mybatis:
      mapper-location: classpath:dynamic/mapper/**/*.xml
      type-aliases-package: com.paladin.qos.dynamic.model
    source[0]:
      name: local
      url: jdbc:mysql://172.16.16.120:3306/qos2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
      username: netin
      password: 123456
      
  
