paladin:
  dynamic-datasource-enabled: 'true'
  dynamic:
    mybatis:
      mapper-location: classpath:dynamic/mapper/**/*.xml
      type-aliases-package: com.paladin.demo.dynamic.model
    source[0]:
      name: mysql
      url: jdbc:mysql://localhost:3306/qos?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
      username: root
    source[1]:
      name: sqlserver
      url: jdbc:sqlserver://172.16.11.35:1433;DatabaseName=test
      username: sa
      password: 123456     
      
  
